version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: nixty_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: nixty
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./backend/src/schema.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build: ./backend
    container_name: nixty_backend
    restart: always
    ports:
      - "3001:3001"
    environment:
      PORT: 3001
      DATABASE_URL: postgres://user:password@db:5432/nixty
      JWT_SECRET: supersecretkey
      ENCRYPTION_KEY: vOVH6sdmpNWjRRIqCc7rdxs01lwHzfr3
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: nixty_frontend
    restart: always
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      INTERNAL_API_URL: http://backend:3001
      NEXT_PUBLIC_API_URL: http://localhost:3001
    depends_on:
      - backend

volumes:
  db_data:
